exclude: (^client/(node_modules|build)|^server/core/migrations)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["-l 100"]
        types: [file, python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--ignore=E231,W503"]
        types: [file, python]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        args: ["-l 100", "-m 3", "--trailing-comma", "--force-grid-wrap=0", "--use-parentheses"]
        types: [file, python]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.3.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: ["--fix", "--max-warnings=0"]
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        files: \.(html|[jt]sx?)$
        types: [file]
        exclude: ^server # prettier doesn't like Django templates
        args: ["--write", "--print-width=100", "--arrow-parens=avoid"]
