version: "3"
services:
  server:
    build:
      context: . # so we can copy over Pipfiles
      dockerfile: ./server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=True
      - DEBUG=True
    volumes:
      - ./server:/server
  client:
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    build: ./client
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules # don't override the node_module folder
  scheduler:
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    build: ./scheduler
    command: yarn start
    ports:
      - "5000:3000"
    volumes:
      - ./scheduler:/scheduler
      - /scheduler/node_modules # don't override the node_module folder
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
