# Generated by Django 3.0.7 on 2020-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
