# Generated by Django 3.0.7 on 2020-06-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='emergency_info_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='liability_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='medliab_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='update_profile_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('student', 'program')},
        ),
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher')),
            ],
            options={
                'unique_together': {('teacher', 'program')},
            },
        ),
        migrations.AlterField(
            model_name='teacherclassregistration',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TeacherRegistration'),
        ),
    ]
