# Generated by Django 3.0.7 on 2020-06-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200619_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentRegistration'),
        ),
    ]
