# Generated by Django 3.0.7 on 2020-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200619_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='update_profile_check',
            field=models.BooleanField(default=False),
        ),
    ]
