# Generated by Django 3.0.7 on 2020-06-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacherregistration_update_profile_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, default='1969-12-31', max_length=8, null=True)),
                ('grad_year', models.IntegerField(blank=True, default=1970, null=True)),
                ('school', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('affiliation', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='espuser',
            name='state',
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
