# Generated by Django 3.0.7 on 2020-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200624_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
