# Generated by Django 3.0.7 on 2020-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200625_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='student_reg_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='teacher_reg_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='availability_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='reg_status',
            field=models.CharField(choices=[('PREF', 'Class Preferences'), ('FROZ', 'Frozen Preferences'), ('CH', 'Change Classes'), ('PRE', 'Pre Program'), ('DAY', 'Day Of'), ('POST', 'Post Program')], default='PREF', max_length=4),
        ),
    ]
