# Generated by Django 3.0.7 on 2020-06-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentregistration_payment_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassregistration',
            old_name='student',
            new_name='studentreg',
        ),
        migrations.RenameField(
            model_name='teacherclassregistration',
            old_name='teacher',
            new_name='teacherreg',
        ),
        migrations.AlterUniqueTogether(
            name='studentclassregistration',
            unique_together={('studentreg', 'clazz')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassregistration',
            unique_together={('teacherreg', 'clazz')},
        ),
    ]
