# Generated by Django 3.0.7 on 2020-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200628_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='reg_status',
            field=models.CharField(choices=[('CLASS_PREFERENCES', 'Class Preferences'), ('FROZEN_PREFERENCES', 'Frozen Preferences'), ('CHANGE_CLASSES', 'Change Classes'), ('PRE_PROGRAM', 'Pre Program'), ('DAY_OF', 'Day Of'), ('POST_PROGRAM', 'Post Program')], default='CLASS_PREFERENCES', max_length=20),
        ),
    ]
