# Generated by Django 3.0.7 on 2020-07-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_scheduledevent_section_timeslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledEvent',
            new_name='ScheduledBlock',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('clazz', 'number')},
        ),
    ]
