# Generated by Django 3.0.7 on 2020-07-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200705_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='core.Program'),
        ),
        migrations.AlterField(
            model_name='scheduledblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', related_query_name='scheduled_block', to='core.Section'),
        ),
        migrations.AlterField(
            model_name='scheduledblock',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', related_query_name='scheduled_block', to='core.Timeslot'),
        ),
        migrations.AlterField(
            model_name='section',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='core.Class'),
        ),
        migrations.AlterField(
            model_name='studentclassregistration',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentclassregs', related_query_name='studentclassreg', to='core.Section'),
        ),
        migrations.AlterField(
            model_name='studentclassregistration',
            name='studentreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classregs', related_query_name='classreg', to='core.StudentRegistration'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentregs', related_query_name='studentreg', to='core.Program'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentregs', related_query_name='studentreg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherclassregistration',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherclassregs', related_query_name='teacherclassreg', to='core.Class'),
        ),
        migrations.AlterField(
            model_name='teacherclassregistration',
            name='teacherreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classregs', related_query_name='classreg', to='core.TeacherRegistration'),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherregs', related_query_name='teacherreg', to='core.Program'),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherregs', related_query_name='teacherreg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', related_query_name='timeslot', to='core.Program'),
        ),
    ]
