# Generated by Django 3.0.7 on 2020-07-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200713_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', related_query_name='classroom', to='core.Program')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledblock',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', related_query_name='scheduled_block', to='core.Classroom'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scheduledblock',
            unique_together={('section', 'timeslot'), ('timeslot', 'classroom')},
        ),
    ]
