# Generated by Django 3.0.7 on 2020-07-22 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200713_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grad_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
