# Generated by Django 3.0.7 on 2020-07-08 23:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200708_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='espuser',
            constraint=models.CheckConstraint(check=models.Q(is_staff=django.db.models.expressions.F('is_superuser')), name='staff_equals_superuser'),
        ),
    ]
