# Generated by Django 3.0.7 on 2020-07-22 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200713_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, max_length=8),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grad_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
