# Generated by Django 3.0.7 on 2020-07-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200724_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'program')},
        ),
    ]
