# Generated by Django 3.0.7 on 2020-07-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200724_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='length',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
