# Generated by Django 3.0.7 on 2020-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherclassregistration',
            old_name='cls',
            new_name='clss',
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
