# Generated by Django 3.0.7 on 2020-06-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200616_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='core.Teacher'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentClassRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
    ]
