# Generated by Django 3.0.7 on 2020-06-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200616_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='affiliation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentclassregistration',
            unique_together={('student', 'clss')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassregistration',
            unique_together={('teacher', 'clss')},
        ),
    ]
