# Generated by Django 3.0.7 on 2020-06-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Program'),
            preserve_default=False,
        ),
    ]
